"""Sound in the page: refused before a gesture, playing after one.

The samples are generated by the app and sent down the meta channel, so nothing here is a file the
browser could have cached — if a buffer exists, the whole path worked: chunked, reassembled by
sequence, decoded at the right rate, and handed to WebAudio.
"""

from __future__ import annotations

import pytest

from termcade.core.music import SAMPLE_RATE

pytestmark = [pytest.mark.browser, pytest.mark.slow]

# Records what the page does with AudioContext without letting it make a sound.
_PROBE = """
(function(){
  window.__audio = {ctx: false, buffers: [], starts: []};
  var AC = window.AudioContext || window.webkitAudioContext;
  if (!AC) return;
  window.AudioContext = function(){
    var c = new AC();
    window.__audio.ctx = true;
    var buffer = c.createBuffer.bind(c);
    c.createBuffer = function(ch, len, rate){
      window.__audio.buffers.push([len, rate]);
      return buffer(ch, len, rate);
    };
    var source = c.createBufferSource.bind(c);
    c.createBufferSource = function(){
      var s = source();
      var start = s.start.bind(s);
      s.start = function(){
        window.__audio.starts.push({loop: s.loop, frames: s.buffer ? s.buffer.length : 0});
        return start.apply(null, arguments);
      };
      return s;
    };
    return c;
  };
  window.AudioContext.prototype = AC.prototype;
})();
"""


@pytest.fixture
def listening(browser, served: str):
    p = browser.new_page(viewport={"width": 844, "height": 390}, is_mobile=True, has_touch=True)
    p.add_init_script(_PROBE)
    p.goto(served, wait_until="networkidle")
    p.wait_for_selector(".xterm-screen", timeout=30_000)
    p.wait_for_timeout(9000)  # the theme is rendered on a worker, then streamed over
    try:
        yield p
    finally:
        p.close()


def test_nothing_sounds_before_the_player_touches_the_page(listening) -> None:
    """Every browser refuses audio to a page nobody has touched. Building the context anyway would
    get it created in a suspended state and the soundtrack would be lost, not delayed."""
    assert listening.evaluate("window.__audio.ctx") is False
    assert listening.evaluate("window.__audio.buffers.length") == 0


def test_the_first_tap_starts_the_soundtrack(listening) -> None:
    """The tune arrives while the page is still untouchable, so it has to be HELD and started on the
    gesture — dropping it is the easy bug, and it sounds exactly like having no music."""
    listening.mouse.click(400, 200)
    listening.wait_for_timeout(4000)

    starts = listening.evaluate("window.__audio.starts")
    assert listening.evaluate("window.__audio.ctx") is True
    assert any(s["loop"] for s in starts), f"nothing is looping — the theme never started: {starts}"


def test_the_samples_arrive_whole_and_at_the_right_rate(listening) -> None:
    """A buffer at the wrong rate plays the tune at the wrong pitch; a short one means the chunks
    were reassembled wrong. Both would sound broken rather than absent."""
    listening.mouse.click(400, 200)
    listening.wait_for_timeout(4000)

    buffers = listening.evaluate("window.__audio.buffers")
    assert buffers, "no audio buffer was ever built"
    assert all(rate == SAMPLE_RATE for _, rate in buffers)
    # The theme is many seconds long; anything short means a truncated reassembly.
    assert max(length for length, _ in buffers) > SAMPLE_RATE * 5
